#name: List R Packages in Docker Container
#
#on:
#push:
#branches:
#- main
#pull_request:
#branches:
#- main
#jobs:
#list_packages:
#runs-on: ubuntu-latest
#
#steps:
#- name: Checkout repository
#uses: actions/checkout@v2
#
#- name: Run Docker container and save output to file
#run: |
##docker run ckrusemd/bookdown-action "R -e 'print(installed.packages())'" > r_packages.txt
##docker run ckrusemd/bookdown-action 'apt-cache search r-cran-' > r_crandocker.txt
#docker run ckrusemd/bookdown-action sh -c ls
#head r_*.txt || echo __no_text__
#
#- name: Commit and push output file
#run: |
#git config --local user.email "actions@github.com"
#git config --local user.name "GitHub Actions"
#git add *.txt || echo __no_est_files__
#git commit -m "Add list of installed R packages"
#git push
#
#


name: Build Docker Container and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker container 
        run: docker build -t umontano/verseh:latest .
        working-directory: .
      
      - name: Archive Docker container as artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-container
          path: .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker container to Docker Hub
        run: docker push umontano/verseh:latest
