name: Build Docker Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker container for ARMv7
        run: docker buildx build --platform linux/arm/v7 -t yourusername/yourimage:latest .
        working-directory: .
      
      - name: Archive Docker container as artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-container
          path: .

