
name: Build Docker Container and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker container 
        run: docker build -t umontano/rhugodown:latest .
        working-directory: .
      
      - name: Archive Docker container as artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-container
          path: .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker container to Docker Hub
        run: docker push umontano/rhugodown:latest
