name: Build Docker Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker container for ARMv7
        run: docker buildx build --platform linux/arm/v7 -o type=local,dest=out.tar .
        working-directory: .
      
      - name: Move Docker container tar file
        run: mv out.tar /github/workspace
        working-directory: .
      
      - name: Archive Docker container tar file
        uses: actions/upload-artifact@v2
        with:
          name: docker-container
          path: /github/workspace/out.tar

