name: platform multi test
on:                                           
  push:                                       
    branches:                                 
      - main                                  
    paths: '**'                         
  workflow_dispatch:                          
jobs:                                         
  build:                                      
    runs-on: ubuntu-latest                    
                                              
    steps:
      - uses: actions/checkout@v4
        name: Checkout code                   

      - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: umontano/rsid
        registry: docker.io
        multiPlatform: true
        platform: linux/arm/v7
        username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
