name: rsid BUILD AND PUSH DOCKER IMAGE

on:
  push:
    branches:
      - main
    paths: '**rsid.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #- name: Build Docker container for ARMv7
        #run: docker buildx build -f rsid.dockerfile --push --pull --platform linux/arm/v7 -t umontano/rsid:latest .
        #,linux/arm64/v8,linux/arm/v5,linux/386,linux/amd64 
        #run: docker buildx build -f rsid.dockerfile --pull --platform linux/arm/v7,linux/arm64/v8,linux/arm/v5,linux/386,linux/amd64 -t umontano/rsid:latest .
      - name: Build and push Docker image
        id: docker_build
        run: |
          docker build . -t umontano/code:latest <<EOF
          FROM alpine:latest
          CMD ["bash"]
          EOF
      
      - name: Archive Docker container as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-container
          path: .

      - name: Push Docker container to Docker Hub
        run: docker push umontano/rsid:latest
