name: Build Docker Container and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: test container
        run: docker image inspect umontano/rsid --format="ignore me"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker container for ARMv7
        run: docker buildx build --pull --platform linux/arm/v7,linux/arm64/v8,linux/arm/v5,linux/386,linux/amd64 -t umontano/rsid:latest rsid.dockerfile
        working-directory: .
      
      - name: Archive Docker container as artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-container
          path: .

      - name: Push Docker container to Docker Hub
        run: docker push umontano/code:latest
