# This is a basic workflow to help you get started with Actions

name: listing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  show_list:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      ## CACHE THE RMARDDOWN AND R DEVTOOLS
      #Cache R Language Installed Packages
      - name: Cache rlang packs
        id: rcache
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-
      ### CONDITIONALLY R BASE AND PACKS INSTALL

      - name: only when no cache rbase and cran
        if: steps.rcache.outputs.cache-hit != 'true'
      ## HUGODOWN DEVTOOLS ONE-LINER
        run: |
          sudo apt-get install -y r-base
          sudo apt-get install -y r-cran-rmarkdown
          sudo apt-get install -y r-cran-remotes
          #sudo apt-get install -y r-cran-devtools
          ## hugodown missing dependencies
          sudo apt-get install -y r-cran-downlit
          sudo apt-get install -y r-cran-rcpptoml
          sudo apt-get install -y r-cran-usethis
          sudo apt-get install -y r-cran-whisker
          sudo apt-get install -y r-cran-whoami

      - name: hugodown devtools_remotes install
        if: steps.rcache.outputs.cache-hit != 'true'
        run: sudo R -e 'remotes::install_github("r-lib/hugodown", dependencies = FALSE, upgrade = "never")' && echo $(date)__SUCCESS_HUGODOWN__ >> zsuccess.z

      ## HUGODOWN RMD RENDER
      - name: render Rmd file
        run: Rscript -e "rmarkdown::render('index.Rmd')"

      ## commit output files
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add *.*
          git commit -m 'actions workflow updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
      #- name: Build Hugo
        #uses: lowply/build-hugo@v0.68.3
#######################################
#######################################
#######################################
